feat(PPDSC-1856): feat(PPDSC-1856)skip-applitools-approval (#1267)
* feat(PPDSC-1856): feat(PPDSC-1856)added test approval first commit

* feat(PPDSC-1856): feat(PPDSC-1856)added requires

* Updated config.yml

* feat(PPDSC-1856): feat(PPDSC-1856)testing when

* feat(PPDSC-1856): feat(PPDSC-1856)testing with a halt

* Updated config.yml

* feat(PPDSC-1856): feat(PPDSC-1856)without steps

* feat(PPDSC-1856): feat(PPDSC-1856)removed job

* feat(PPDSC-1856): feat(PPDSC-1856)added other scnarios

* feat(PPDSC-1856): feat(PPDSC-1856)added comps and site combo

* feat(PPDSC-1856): feat(PPDSC-1856)added all tests back

* feat(PPDSC-1856): feat(PPDSC-1856)added all tests to doc site

* feat(PPDSC-1856): feat(PPDSC-1856)removed comments

* feat(PPDSC-1856): feat(PPDSC-1856)added can merge approval

* Updated config.yml

* Updated config.yml

* feat(PPDSC-1856): feat(PPDSC-1856)added can merge approval

* feat(PPDSC-1856): feat(PPDSC-1856)added test visual comps to can merge

* feat(PPDSC-1856): feat(PPDSC-1856)changed site to docds

* feat(PPDSC-1856): feat(PPDSC-1856)removed off of can merge

* Updated config.yml

* Updated config.yml

* feat(PPDSC-1856): feat(PPDSC-1856)added testing job

* feat(PPDSC-1856): feat(PPDSC-1856)no errors on waiter

* Updated config.yml

* feat(PPDSC-1856): feat(PPDSC-1856)added circle branch

* feat(PPDSC-1856): feat(PPDSC-1856)updated curl

* feat(PPDSC-1856): feat(PPDSC-1856)added long way round

* feat(PPDSC-1856): feat(PPDSC-1856)added build story to no changes

* feat(PPDSC-1856): reverse

* Updated config.yml

* feat(PPDSC-1856): csorted conflicts

* feat(PPDSC-1856): feat(PPDSC-1856)reset

* feat(PPDSC-1856): feat(PPDSC-1856)added script

* feat(PPDSC-1856): feat(PPDSC-1856)added new approval

* feat(PPDSC-1856): feat(PPDSC-1856)added checkout

* feat(PPDSC-1856): feat(PPDSC-1856)added const request

* feat(PPDSC-1856): added install_deps before test_trigger

* feat(PPDSC-1856): feat(PPDSC-1856)added attach workspace

* feat(PPDSC-1856): feat(PPDSC-1856)added |

* feat(PPDSC-1856): move echo up

* feat(PPDSC-1856): add github-cli for adding bash

* feat(PPDSC-1856): remove gh and removed dollar and brakets

* feat(PPDSC-1856): added echo for parameter

* feat(PPDSC-1856): added waiter and new approach

* feat(PPDSC-1856): echoing variables

* feat(PPDSC-1856): installing jq and echoing

* feat(PPDSC-1856): removed double dollar sign

* feat(PPDSC-1856): printing stuff

* feat(PPDSC-1856): printing stuff

* feat(PPDSC-1856): changed how we add vars

* feat(PPDSC-1856): passing npp context

* feat(PPDSC-1856): used newskit dev context

* feat(PPDSC-1856): fixing applitool waiter too

* feat(PPDSC-1856): try timeout

* feat(PPDSC-1856): trying removing jq

* feat(PPDSC-1856): improving naming

* feat(PPDSC-1856): trying removing -checkout

* feat(PPDSC-1856): changed context where auth comes from

* feat(PPDSC-1856): feat(PPDSC-1856)changed icanmerge placement

* feat(PPDSC-1856): feat(PPDSC-1856)added test_visual_docs_two

* feat(PPDSC-1856): feat(PPDSC-1856)updated test_visual_docs

* feat(PPDSC-1856): feat(PPDSC-1856)added done

* feat(PPDSC-1856): feat(PPDSC-1856)added fi

* feat(PPDSC-1856): feat(PPDSC-1856)testing to fail

* feat(PPDSC-1856): feat(PPDSC-1856)added halt

* feat(PPDSC-1856): feat(PPDSC-1856)added exit

* feat(PPDSC-1856): refactired test v chanfges to be a command

* feat(PPDSC-1856): fixing comman invokation

* feat(PPDSC-1856): feat(PPDSC-1856)deleted script and request

* feat(PPDSC-1856): feat(PPDSC-1856)yarn locl

* feat(PPDSC-1856): removed extra lines

* feat(PPDSC-1856): renamed waiter to checker

* feat(PPDSC-1856): feat(PPDSC-1856)deleted txt file

* feat(PPDSC-1856): feat(PPDSC-1849)added i_have_merged_applitools

Co-authored-by: Vanals <marco91vanali@gmail.com>

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -227,7 +227,43 @@ commands:
               circleci-agent step halt
             fi
 
-jobs:
+  run_test_visual_changes:
+    description: 'Run the Applitool tests for docs visual changes'
+    steps:
+      - checkout
+      - attach_workspace:
+          at: ~/project
+      - run:
+          name: 'Setup Applitools environment variables'
+          <<: *applitools_defaults
+      - run:
+          name: Run Applitools Docs Site Visual Tests
+          command: make e2e_visual_test_docs
+      - run:
+          name: Close the Applitools Batch
+          command: curl --request DELETE --dump-header - "https://eyesapi.applitools.com/api/sessions/batches/$APPLITOOLS_BATCH_ID/close/bypointerid/?apiKey=$APPLITOOLS_API_KEY"
+      - store_artifacts:
+          path: cypress/screenshots
+      - store_artifacts:
+          path: cypress/videos
+      - slack/status:
+          <<: *slack_status
+
+jobs: 
+  can_i_merge_checker: 
+    executor: node
+    steps:
+      - run: 
+          name: 'Waiting for "no_visual_changes" or "test_visual_docs"'
+          command: |
+            if [[ $(curl --location --request GET "https://circleci.com/api/v2/workflow/${CIRCLE_WORKFLOW_ID}/job" --header "Circle-Token: ${CIRCLECI_BASE_AUTH}"| jq -r '.items[]|select(.name == "no_visual_changes" or .name == "test_visual_docs" or .name == "test_visual_docs_2")|.status' | grep -c "success") -gt 0 ]]
+            then 
+              echo "Passed!"
+            else 
+              echo "Failed!"
+              exit 1
+            fi
+
   install_deps:
     <<: *working_directory
     executor: node-large
@@ -250,7 +286,8 @@ jobs:
             - node_modules/*
             - src/version-number.json
       - slack/status:
-          <<: *slack_status   
+          <<: *slack_status
+
   install_cypress:
     <<: *cypress_defaults
     executor: cypress
@@ -566,24 +603,13 @@ jobs:
     <<: *cypress_defaults
     executor: cypress
     steps:
-      - checkout
-      - attach_workspace:
-          at: ~/project
-      - run:
-          name: 'Setup Applitools environment variables'
-          <<: *applitools_defaults
-      - run:
-          name: Run Applitools Docs Site Visual Tests
-          command: make e2e_visual_test_docs
-      - run:
-          name: Close the Applitools Batch
-          command: curl --request DELETE --dump-header - "https://eyesapi.applitools.com/api/sessions/batches/$APPLITOOLS_BATCH_ID/close/bypointerid/?apiKey=$APPLITOOLS_API_KEY"
-      - store_artifacts:
-          path: cypress/screenshots
-      - store_artifacts:
-          path: cypress/videos
-      - slack/status:
-          <<: *slack_status
+      - run_test_visual_changes
+
+  test_visual_docs_2:
+    <<: *cypress_defaults
+    executor: cypress
+    steps:
+      - run_test_visual_changes
 
   test_e2e_comps:
     <<: *cypress_defaults
@@ -1006,24 +1032,52 @@ workflows:
           requires:
             - build_docs
             - install_cypress
+
       # PR jobs
-      - run_visual_tests:
+        ## Visual changes approval jobs
+      - no_visual_changes:
           <<: *only_pr
           type: approval
           requires:
             - build_storybook
+      - docs_and_comps_visual_changes:
+          <<: *only_pr
+          type: approval
+          requires:
+            - build_storybook
+      - docs_visual_changes:
+          <<: *only_pr
+          type: approval
+          requires:
+            - build_storybook
+        # end visual changes approval jobs
       - test_visual_comps:
           <<: *only_pr
           context: ncu-product-platforms-context
           requires:
-            - run_visual_tests
+            - docs_and_comps_visual_changes
       - test_visual_docs:
           <<: *only_pr
           context: ncu-product-platforms-context
           requires:
             - build_docs
-            - test_visual_comps
             - install_cypress
+            - test_visual_comps
+      - test_visual_docs_2:
+          <<: *only_pr
+          context: ncu-product-platforms-context
+          requires:
+            - build_docs
+            - install_cypress
+            - docs_visual_changes
+      - can_i_merge_checker:  
+          <<: *only_pr   
+          context: ncu-product-platforms-context
+          requires:
+            - i_have_merged_applitools
+      - i_have_merged_applitools:
+          <<: *only_pr
+          type: approval
       - init_aws:
           <<: *ignore_trigger_release
           context: ncu-product-platforms-context
