fix(PPDSC-2611): full checks

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -653,13 +653,17 @@ jobs:
             export PR_BRANCH_NAME=feat/PPDSC-2694-rem-support
             echo "Found branch name: ${PR_BRANCH_NAME}"
             export PERCY_TOKEN=$PERCY_COMPS_TOKEN
-            export UPDATES_REQUIRED=$(npx -y run-func scripts/check-baseline-updates.js run $PR_BRANCH_NAME)
-            if [ $UPDATES_REQUIRED = "true" ]; then
+            export CHECK_UPDATES=$(npx -y run-func scripts/check-baseline-updates.js run $PR_BRANCH_NAME)
+            echo "Result from check-baseline-updates.js: ${CHECK_UPDATES}"
+            if [ $CHECK_UPDATES = "UPDATES_REQUIRED" ]; then
               echo "Baseline updates required; continuing job."
               export PERCY_PARTIAL_BUILD=1
-            else
-              echo "No baseline updates required; finishing job." &&
+            elif [ $CHECK_UPDATES = "NO_UPDATES_REQUIRED" ]; then
+              echo "No baseline updates required; finishing job."
               circleci-agent step halt
+            else
+              echo "Error checking PR"
+              exit 1
             fi
 
   test_job_2:
@@ -674,13 +678,17 @@ jobs:
             export PR_BRANCH_NAME=docs/PPDSC-2665-date-time-docs
             echo "Found branch name: ${PR_BRANCH_NAME}"
             export PERCY_TOKEN=$PERCY_COMPS_TOKEN
-            export UPDATES_REQUIRED=$(npx -y run-func scripts/check-baseline-updates.js run $PR_BRANCH_NAME)
-            if [ $UPDATES_REQUIRED = "true" ]; then
+            export CHECK_UPDATES=$(npx -y run-func scripts/check-baseline-updates.js run $PR_BRANCH_NAME)
+            echo "Result from check-baseline-updates.js: ${CHECK_UPDATES}"
+            if [ $CHECK_UPDATES = "UPDATES_REQUIRED" ]; then
               echo "Baseline updates required; continuing job."
               export PERCY_PARTIAL_BUILD=1
-            else
-              echo "No baseline updates required; finishing job." &&
+            elif [ $CHECK_UPDATES = "NO_UPDATES_REQUIRED" ]; then
+              echo "No baseline updates required; finishing job."
               circleci-agent step halt
+            else
+              echo "Error checking PR"
+              exit 1
             fi
 
   test_job_3:
@@ -719,13 +727,17 @@ jobs:
             export PR_BRANCH_NAME=invalidbranchname
             echo "Found branch name: ${PR_BRANCH_NAME}"
             export PERCY_TOKEN=$PERCY_COMPS_TOKEN
-            export UPDATES_REQUIRED=$(npx -y run-func scripts/check-baseline-updates.js run $PR_BRANCH_NAME)
-            if [ $UPDATES_REQUIRED = "true" ]; then
+            export CHECK_UPDATES=$(npx -y run-func scripts/check-baseline-updates.js run $PR_BRANCH_NAME)
+            echo "Result from check-baseline-updates.js: ${CHECK_UPDATES}"
+            if [ $CHECK_UPDATES = "UPDATES_REQUIRED" ]; then
               echo "Baseline updates required; continuing job."
               export PERCY_PARTIAL_BUILD=1
-            else
-              echo "No baseline updates required; finishing job." &&
+            elif [ $CHECK_UPDATES = "NO_UPDATES_REQUIRED" ]; then
+              echo "No baseline updates required; finishing job."
               circleci-agent step halt
+            else
+              echo "Error checking PR"
+              exit 1
             fi
 
   comps_tests_conditional_run_to_update_baselines:
