fix(PPDSC-2611): fix pipeline (#596)
* fix(PPDSC-2611): fix pipeline

* fix(PPDSC-2611): update pipeline logic

* fix(PPDSC-2611): correct loop

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -631,13 +631,17 @@ jobs:
             export PR_BRANCH_NAME=$(gh pr list --search $CIRCLE_SHA1 --state merged --json headRefName --jq '.[].headRefName')
             echo "Found branch name: ${PR_BRANCH_NAME}"
             export PERCY_TOKEN=$PERCY_COMPS_TOKEN
-            export UPDATES_REQUIRED=$(npx -y run-func scripts/check-baseline-updates.js run $PR_BRANCH_NAME)
-            if [ $UPDATES_REQUIRED = "true" ]; then
+            export CHECK_UPDATES=$(npx -y run-func scripts/check-baseline-updates.js run $PR_BRANCH_NAME)
+            echo "Result from check-baseline-updates.js: ${CHECK_UPDATES}"
+            if [ $CHECK_UPDATES = "UPDATES_REQUIRED" ]; then
               echo "Baseline updates required; continuing job."
               export PERCY_PARTIAL_BUILD=1
-            else
-              echo "No baseline updates required; finishing job." &&
+            elif [ $CHECK_UPDATES = "NO_UPDATES_REQUIRED" ]; then
+              echo "No baseline updates required; finishing job."
               circleci-agent step halt
+            else
+              echo "Error checking PR"
+              exit 1
             fi
       - run_test_visual_comps_percy
       - slack/notify:
@@ -655,14 +659,18 @@ jobs:
           command: |
             export PR_BRANCH_NAME=$(gh pr list --search $CIRCLE_SHA1 --state merged --json headRefName --jq '.[].headRefName')
             echo "Found branch name: ${PR_BRANCH_NAME}"
-            export PERCY_TOKEN=$PERCY_COMPS_TOKEN
-            export UPDATES_REQUIRED=$(npx -y run-func scripts/check-baseline-updates.js run $PR_BRANCH_NAME)
-            if [ $UPDATES_REQUIRED = "true" ]; then
+            export PERCY_TOKEN=$PERCY_DOCSITE_TOKEN
+            export CHECK_UPDATES=$(npx -y run-func scripts/check-baseline-updates.js run $PR_BRANCH_NAME)
+            echo "Result from check-baseline-updates.js: ${CHECK_UPDATES}"
+            if [ $CHECK_UPDATES = "UPDATES_REQUIRED" ]; then
               echo "Baseline updates required; continuing job."
               export PERCY_PARTIAL_BUILD=1
-            else
-              echo "No baseline updates required; finishing job." &&
+            elif [ $CHECK_UPDATES = "NO_UPDATES_REQUIRED" ]; then
+              echo "No baseline updates required; finishing job."
               circleci-agent step halt
+            else
+              echo "Error checking PR"
+              exit 1
             fi
       - run_test_visual_docs_percy
       - slack/notify:
