fix(PPDSC-2611): Revert "chore(PPDSC-2611): fewer tests for baseline updates (#588)"
This reverts commit fd4d458849c729974aec1ea8a087fad642543ede.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -803,17 +803,15 @@ jobs:
       - run:
           name: 'Check if updates required'
           command: |
-            export PR_BRANCH_NAME=$(gh pr list --search $CIRCLE_SHA1 --state merged --json headRefName --jq '.[].headRefName')
-            echo "Found branch name: ${PR_BRANCH_NAME}"
-            export PERCY_TOKEN=$PERCY_COMPS_TOKEN
-            export UPDATES_REQUIRED=$(npx -y run-func scripts/check-baseline-updates.js run $PR_BRANCH_NAME)
-            if [ $UPDATES_REQUIRED = "true" ]; then
-              echo "Baseline updates required; continuing job."
-              export PERCY_PARTIAL_BUILD=1
-            else
-              echo "No baseline updates required; finishing job." &&
-              circleci-agent step halt
-            fi
+            {
+                export PR_BRANCH_NAME=$(gh pr list --search $CIRCLE_SHA1 --state merged --json headRefName --jq '.[].headRefName') &&
+                echo "Found branch name: ${PR_BRANCH_NAME}" &&
+                node scripts/check-baseline-updates.js $PR_BRANCH_NAME "comps" &&
+                echo "No baseline updates required; finishing job." &&
+                circleci-agent step halt
+            } || {
+                echo "Baseline updates required; continuing job."
+            }
       - run_test_visual_comps_percy
       - slack/notify:
           <<: *slack_notify
@@ -828,17 +826,15 @@ jobs:
       - run:
           name: 'Check if updates required'
           command: |
-            export PR_BRANCH_NAME=$(gh pr list --search $CIRCLE_SHA1 --state merged --json headRefName --jq '.[].headRefName')
-            echo "Found branch name: ${PR_BRANCH_NAME}"
-            export PERCY_TOKEN=$PERCY_COMPS_TOKEN
-            export UPDATES_REQUIRED=$(npx -y run-func scripts/check-baseline-updates.js run $PR_BRANCH_NAME)
-            if [ $UPDATES_REQUIRED = "true" ]; then
-              echo "Baseline updates required; continuing job."
-              export PERCY_PARTIAL_BUILD=1
-            else
-              echo "No baseline updates required; finishing job." &&
-              circleci-agent step halt
-            fi
+            {
+                export PR_BRANCH_NAME=$(gh pr list --search $CIRCLE_SHA1 --state merged --json headRefName --jq '.[].headRefName') &&
+                echo "Found branch name: ${PR_BRANCH_NAME}" &&
+                node scripts/check-baseline-updates.js $PR_BRANCH_NAME "docsite" &&
+                echo "No baseline updates required; finishing job." &&
+                circleci-agent step halt
+            } || {
+                echo "Baseline updates required; continuing job."
+            }
       - run_test_visual_docs_percy
       - slack/notify:
           <<: *slack_notify
